apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.27.0
  name: alertmanager-main
  namespace: metrics
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    templates:
      - /etc/alertmanager/config/*.tmpl
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        target_match:
          severity_re: warning|info
        source_match:
          severity: critical
      - equal:
          - namespace
          - alertname
        target_match:
          severity_re: info
        source_match:
          severity: warning
    receivers:
      - name: dingding1
        webhook_configs:
          - url: http://dingtalk:8060/dingtalk/webhook1/send
            http_config: {}
            send_resolved: false
    route:
      group_by: []
      group_interval: 5m
      group_wait: 30s
      receiver: dingding1
      repeat_interval: 12h
      routes:
        - receiver: dingding1
          continue: true
          group_interval: 1m
          repeat_interval: 1h
          routes: []
          match:
            severity: warning
type: Opaque
